version: '3.9'

services:
  socpost-postgres:
    image: postgres:14.5
    container_name: socpost-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: socpost-local-pwd
      POSTGRES_USER: socpost-local
      POSTGRES_DB: soccpost-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - socpost-network
      
  socpost-redis:
    image: redis:7.2
    container_name: socpost-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - socpost-network


volumes:
  postgres-volume:
    external: false

networks:
  socpost-network:
    driver: bridge